# Generated by Django 4.2 on 2023-04-22 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('per_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_nascimento', models.DateField()),
                ('per_pessoa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
