# Generated by Django 4.2.6 on 2023-10-27 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno_Csv',
            fields=[
                ('alu_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('alu_nome', models.CharField(max_length=50, null=True, verbose_name='Aluno')),
                ('alu_matricula', models.CharField(max_length=20, null=True, verbose_name='Matricula')),
                ('alu_turma', models.CharField(max_length=20, null=True, verbose_name='Turma')),
                ('alu_vinculado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='curso_instituicao',
            fields=[
                ('curs_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('curs_nome', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('doce_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('doce_instituicao_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('per_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_pergunta', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUser',
            fields=[
                ('per_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_nascimento', models.DateField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('per_tell', models.CharField(blank=True, max_length=14)),
                ('tipo', models.CharField(blank=True, max_length=1)),
                ('per_foto', models.FileField(blank=True, null=True, upload_to='fotos_usuario/%Y/%m/')),
                ('per_detalhe', models.TextField(blank=True)),
                ('per_habilidade', models.TextField(blank=True)),
                ('per_pessoa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Docente_curso',
            fields=[
                ('doce_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('doce_curso_instituicao_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_instituicao')),
                ('doce_docente_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='doce_perfil_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser'),
        ),
        migrations.AddField(
            model_name='curso_instituicao',
            name='curs_perfil_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser'),
        ),
        migrations.CreateModel(
            name='curso_aluno',
            fields=[
                ('curs_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('curs_insituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_instituicao')),
                ('curs_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('cert_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('cert_nome_curso', models.CharField(max_length=75)),
                ('cert_instituicao', models.CharField(max_length=50)),
                ('cert_arquivo', models.FileField(blank=True, null=True, upload_to='certificados/%Y/%m/')),
                ('cert_pessoa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('ava_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ava_nota', models.IntegerField(blank=True, null=True)),
                ('ava_curso_aluno_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_aluno')),
                ('ava_docente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
                ('ava_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
                ('ava_pergunta_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno_avaliado',
            fields=[
                ('alu_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('alu_curso_aluno_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_aluno')),
                ('alu_docente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
                ('alu_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
    ]
