# Generated by Django 4.2 on 2023-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='per_nascimento',
            field=models.DateField(verbose_name=('%d-%m-%Y', '%Y-%m-%d')),
        ),
    ]
