# Generated by Django 4.2 on 2023-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_alter_certificados_cert_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='perfiluser',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'Aluno'), ('E', 'Empresa'), ('I', 'Instituição'), ('D', 'Docente')], default='A', max_length=1),
        ),
    ]
