# Generated by Django 4.2 on 2023-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_perfiluser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_matricula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_turma',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
