# Generated by Django 4.2 on 2023-05-18 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0010_alter_aluno_csv_alu_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_matricula',
            field=models.CharField(max_length=20, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_turma',
            field=models.CharField(max_length=20, null=True, verbose_name='Turma'),
        ),
        migrations.CreateModel(
            name='curso_instituicao',
            fields=[
                ('curs_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('curs_nome', models.CharField(max_length=45, null=True)),
                ('curs_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
        migrations.CreateModel(
            name='curso_aluno',
            fields=[
                ('curs_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('curs_insituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_instituicao')),
                ('curs_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
    ]
