# Generated by Django 4.2 on 2023-05-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_perfiluser_per_datlhe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiluser',
            old_name='per_datlhe',
            new_name='per_detalhe',
        ),
    ]
