# Generated by Django 4.2 on 2023-05-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0014_rename_per_datlhe_perfiluser_per_detalhe'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='per_foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos_usuario/%Y/%m/'),
        ),
    ]
