# Generated by Django 4.2 on 2023-05-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_perfiluser_per_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='cert_pessoa_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser', verbose_name='Usuario'),
        ),
    ]
