# Generated by Django 4.2 on 2023-05-24 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0017_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='doce_instituicao_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docente',
            name='doce_perfil_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser'),
        ),
    ]
