# Generated by Django 4.2 on 2023-06-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0018_docente_doce_instituicao_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_csv',
            name='alu_vinculado',
            field=models.BooleanField(default=True),
        ),
    ]
