# Generated by Django 4.2 on 2023-06-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_aluno_csv_alu_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno_csv',
            name='alu_vinculado',
            field=models.BooleanField(default=False),
        ),
    ]
