# Generated by Django 4.2 on 2023-06-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_alter_perfiluser_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
