# Generated by Django 4.2 on 2023-06-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0022_alter_perfiluser_cpf_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('per_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('per_pergunta', models.CharField(blank=True, max_length=155, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente_curso',
            fields=[
                ('doce_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('doce_curso_instituicao_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_instituicao')),
                ('doce_docente_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
            ],
        ),
    ]
