# Generated by Django 4.2.1 on 2023-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0023_perguntas_docente_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso_aluno',
            name='curs_avaliacao',
            field=models.BooleanField(default=False),
        ),
    ]
