# Generated by Django 4.2.1 on 2023-06-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_curso_aluno_curs_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso_aluno',
            name='curs_avaliacao',
        ),
        migrations.CreateModel(
            name='Aluno_avaliado',
            fields=[
                ('alu_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('alu_docente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
                ('alu_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
    ]
