# Generated by Django 4.2.1 on 2023-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_remove_curso_aluno_curs_avaliacao_aluno_avaliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno_avaliado',
            name='alu_curso_aluno_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_aluno'),
        ),
    ]
