# Generated by Django 4.2 on 2023-06-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_aluno_avaliado_alu_curso_aluno_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('ava_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ava_nota', models.IntegerField(blank=True, null=True)),
                ('ava_curso_aluno_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.curso_aluno')),
                ('ava_docente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.docente')),
                ('ava_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
    ]
