# Generated by Django 4.2 on 2023-06-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_avaliacao_ava_pergunta_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='per_habilidade',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
