# Generated by Django 4.2 on 2023-04-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0006_alter_certificados_cert_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVagas',
            fields=[
                ('vag_cod', models.BigAutoField(primary_key=True, serialize=False)),
                ('vag_nome', models.CharField(max_length=50)),
                ('vag_tell', models.CharField(max_length=50)),
                ('vag_email', models.EmailField(max_length=80)),
                ('vag_endereco', models.CharField(max_length=20)),
                ('vag_descricao', models.CharField(max_length=100)),
                ('vag_funcao', models.CharField(max_length=50)),
                ('vag_beneficio', models.CharField(max_length=100)),
                ('vag_divulgado', models.DateField()),
                ('vag_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
            ],
        ),
    ]
