# Generated by Django 4.2 on 2023-04-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvagas',
            name='vag_divulgado',
        ),
    ]
