# Generated by Django 4.2 on 2023-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_vagas', '0002_remove_postvagas_vag_divulgado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvagas',
            name='vag_email',
            field=models.EmailField(blank=True, max_length=80, null=True),
        ),
    ]
