# Generated by Django 4.2 on 2023-05-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0015_perfiluser_per_foto'),
        ('post_vagas', '0003_alter_postvagas_vag_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga_cadastradas',
            fields=[
                ('vcad_codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('vcad_perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfiluser')),
                ('vcad_postVaga_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_vagas.postvagas')),
            ],
        ),
    ]
