# Generated by Django 4.2 on 2023-05-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_vagas', '0006_rename_vag_perfil_fk_postvagas_vag_usuario_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvagas',
            name='vag_beneficio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postvagas',
            name='vag_descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postvagas',
            name='vag_endereco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postvagas',
            name='vag_funcao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postvagas',
            name='vag_nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postvagas',
            name='vag_tell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
